[project]
name = "openeo-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openeo>=0.42.1",
    "requests>=2.32.4",
]
